language: go

branches:
  only:
    - master

install:
  - go get github.com/spf13/hugo
  - rm -rf public || exit 0 # cleanup previous run

script:
  - hugo # generate!

deploy:
  provider: s3
  local-dir: public
