language: go

branches:
  only:
    - master

install:
  - go get -tags 'extended' github.com/gohugoio/hugo
  - rm -rf public || exit 0 # cleanup previous run

script:
  - hugo # generate!

deploy:
  provider: s3
  local-dir: public
