language: go
branches:
  only:
  - master
install:
#- go get gopkg.in/gohugoio/hugo.v.54.0
#- go get github.com/gohugoio/hugo
#- go get -d -v github.com/gohugoio/hugo@v0.54.0
#- go build -o hugo -tags 'extended' github.com/gohugoio/hugo
#- wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Linux-64bit.deb
#- sudo dpkg -i /tmp/hugo.deb
- wget -O /tmp https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Linux-64bit.tar.gz
- tar -xzf /tmp/hugo_extended_0.54.0_Linux-64bit.tar.gz -C /tmp
- npm install -g autoprefixer
- npm install -g postcss-cli
- rm -rf public || exit 0
script:
- /tmp/hugo version
- /tmp/hugo
deploy:
  provider: s3
  local-dir: public
  region: us-west-2
  skip_cleanup: true
  server_side_encryption: true
  bucket:
    secure: bvvsaSwUF2Jse4zLOUDXS2m3VFRZuhAg3/mOH4+iWKv7dF97k+JmH33O/a4dSpczpMtxr8r6raNeTLpQVblwSmiCwCj568oo8V2iXlPgxDIjBNo1lILsjn/aQE115dQMxbayv5FJbwCuqUWaDPXcAjaJfo08M19ePvzNNDyohOsyfd8dJgJiS9v4tY3tTaLA7OpA277cKLipzL4CSR4J9kW5sMt72ARQhfqDrWshDdKQk8oJBlPcjmnKrYlppzKhascGtupPJxxrOh89ktFWoV4jJSBuoguDv272TAQiMrvSpFpG3ZOfHq0VBQ9H9j79FuI2HSPT4/KscN1MsQE9AflwctDk7/gsjeTwzPYZVZmU/Uay6pY5uTVs2pIEv7E13Tk85vP81C7aLlsHBgFWsdRCPbHT4mNm3A46TnTwUHrcz13VyC+EnIEwrfqCgnIlfO24z/nBqxWCt7lzPF+PcjcZcWI3UirU0OX5j5XJHYXfDKsWlv/r73yZD+WhKXSkYUkyOEwahODkeI5UZN4lvc5KXEqceObYgpf1FgxCMD1pRKWRVZRGaTAqcqN9d/oGzrZR6rnyaZsIElPgM8tb+scevCAhbmT1OsFQ6teQ+o+sPj3JMvyH4Mh6vHbAX9MXf9rPSGP4we2ETotI++G7nYoTiMhjkKpBm7ZRRptQVj8=
  access_key_id:
    secure: eAICn87Vu1cHz2evRFgeXINkI4jZRzpNnqib+jXunWQANCux4EwBh/KsoiHzQP6Kd+AUlxTEyg/s5UKvQjtfU2qHW0VNhSB6V7YOPBEDml/FEnDY6E3wObekHEi0F7ginYVGU4fhmy+BTVTnNAMTcFHMz6clbe/66A1XH/QmGhR3sMThUyj1Q+4ixCT6N0Yhlxqy8qWEIqLWaXdPXtHZ9bjskaL2B2AaDXLMRAWICfQ2gSfP6oAIGvtFJfTNUB4TwTlUZfQp6GuiK8v2EuW0QFtSfXl7jmU2GTj92IP08nNd3BqpiUtQQ2vWeHubNGOri+wU+JPA5kVgzOTyYHZJ3QN5ti3bk3tbcCmtRHjrMcylfx3O0OgvsM2DiqEmVMdqdFrY7QeVzmItLfHn9A8M0Xo0H+R6IPxbnzxdcon9/le6+nZq6XysVvpSM3t9VzjHye0iAEc+n2votLeqifWR8B0hFu8T37vOc5qWsjS8Kdni80hELG7/sdeHRM3Fb8HgnOCrBCrQ2p2R6KxgrwLXoPLWL9k8cxyNbZX6k+8wgTGjXcdV/TYhTpJIdZ6RVTp9PiGgKaHXkXIIOpwBOOCrYiVm47JRePf1tmDhcUnaYA/ApqsHLoQn6jBE4bF84UJHsNBM0QJEDRJp5DfrvcCkivdnlsRgrpbTe/HhIiVhhvY=
  secret_access_key:
    secure: gor5eGzpEl4W97LWDUeqdWYrQmxmiXdgwnRQogBwYCd9OAxtnHlztp+gdHH0j8I2/50GfgHwrhr/CSvzsGVHs+3BWk7OPovV/48UXxnJuzPk+pwn0iI4iI7e1wAfJsryPl/rXA0wLtyVttfKBhu9Ox9Q/MGYm6IKr8AXBZ2UgnxLGAhjk9OyQFOL9skMHcKnI40uOPXZLucoNSEoYT6u55DikbS/6H1WaHgrBpaqBd/ZBNi2krcpMNMcG/XYgc4dQ2Dzb79zBmKOrsHClgC1S8EOJeDjD0p7Jg+NnwQG3MEhnQxh5SRgMEAp4z4b23VbymoJTLmJpZKgavgu/0LnmFxavC4JeOOzW2G3qWfv0pWxpoGtnWTlkAnqPIdLoJNBf2GU71RRABMEEkZt/1nkMHKHQ02IAKBOWJydsl9nNR243asFn3B96ExZBm1F3X5BASHGu91NGQqNONWX3gsX2dSEfDOSQFU+fvuB+Lw8+j2WKU8oiKYZkUydd7cSEINh3dLFC4fwafHkr6RMdW+CopgbuDAQNr3FJ6Icjer6Y1TSK5lBnflmn//jxHEwt/fKsXXPXbqxJBZMLbdf5D/NCNPmnI8qyIFYiGUPsZvRTKSMSF3MZGuEc7mdoG9QvyXLsh7mvNyIWs1rP/w8BKMfZPbnUj8jS7xPpwqG6AZaKNg=
notifications:
  slack:
    secure: A2t2DfzyRHo3qlBqIV/5YRIyGowWFLbou2DqfgndjEOaKBI3AR2/PCCUYKuYNl57xO8/9IN9Kaw+3dvVYSzap4L8E6wpX808M77LKd3tb2kIhRphr5qai3JyMiRGWIfTugGanUtMkAb0mVymsu/BF9wGfgg/djr3D1+SoYSBoFaej4Jusy/d2OzRY0IT3lweJT/cNzi4YqD+QdV02JVK4APjGJZONvQxiA9HCBcdeojZNLgcJA9EJIjKI3lbKwqTOsegtBeR4rNbZpFGknI0cOhfcsFILlhhk9yRBCkirvGgAPZK/snSLzQVrKT7f6RPkxK9HaR9sl5b3EXF2s41U+5QZfI3t8rkFh7t0H+Vv3bnJiVq6bZnvePzySd2JrvThRDkNOMZ62klA9Z8F/Jp7n4z45yRHaSj3WtIQKKupgWeekfNNCm+8zZekvAGpFbwUaPVxMhv94bh9EEBiDRfg9nmgDnDBROc/6jad7Ij/q7CdeLafft/BHg+HW2WoIt4p/A8J//XnvciTnVbvLvAN2LqG+uNGmd1oAFDbUbrlLM8DONg7CHWtyureJkr9XJDDqWhye2aY2xCZ5HEhQXaifOBb8NRQyXri42G0N2XbgB6rxaHAi1gNRtoK205aUrsmQosx+3dngX633hj19hQQ0xvivRWgiFS14GbfLJ95C4=
