baseURL                     = "https://tidyrisk.org/"      # Your domain name. Must end with "/"
theme                       = "introduction"
DefaultContentLanguage      = "en"                         # languageCode
# disqusshortname           = ""                           # Enable Disqus for comments https://gohugo.io/content-management/comments
# googleAnalytics           = ""                           # Enable Google Analytics https://gohugo.io/templates/internal/#google-analytics

[params]
    themeStyle              = "light"                      # Choose 'light' or 'dark'
    favicon                 = "/img/fav.ico"
    showRSSButton           = false
    fadeIn                  = false                         # Turn on/off the fade-in effect
    dateFormat              = "Jan 2, 2006"
    email                   = "davidski@deadheaven.com"    # Shows in contact section, or leave blank to omit
    #customCSS               = []                          # Include custom css files e.g. ["css/foo.css", "css/bar.css"]

    # Configure the home page
    [params.home]
        introHeight             = "fullheight"                  # Input either 'medium' or 'large' or 'fullheight'
        showLatest              = false                    # Show latest blog post summary
        showAllPosts            = false                    # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
        numberOfProjectsToShow  = 2                        # Maximum number of projects to show on home page. Unset or comment out to show all projects.

        localTime               = false                    # Show your current local time in contact section
        timeZone                = "America/Los_Angeles"    # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

    [params.projects]
        useTwoColumns       = true                         # use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter            = true
        facebook           = false
        googlePlus         = false
        pinterest          = false

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Find icon names here: http://fontawesome.io/cheatsheet/
    [[params.social]]
        url  = "https://twitter.com/dseverski"
        icon = "twitter"
    [[params.social]]
        url  = "https://github.com/davidski"
        icon = "github"
    [[params.social]]
        url  = "https://linkedin.com/in/davidseverski"
        icon = "linkedin"

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "tidyrisk - Making Quant Risk Tidy" # Site title
        [languages.en.params]
            description             = "Quantitative Risk Management in R"             # Max 160 characters show in search results
            footerText              = ""                                # Text to override default footer text (markdown allowed)