name: Build site

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Set a branch to deploy
      - main  # Set a branch to deploy

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install NPM dependencies
        run: |
          npm install autoprefixer@9.8.6
          npm install postcss postcss-cli

      - name: Build
        run: hugo

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ secrets.AWS_SESSION_NAME }}
          aws-region: us-west-2

      - name: Copy files to the production site with the AWS CLI
        run: |
          aws s3 cp --recursive public s3://${{ secrets.DEPLOY_BUCKET }}/

